/**
 *
 *  XxlJobLogglue.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "XxlJobLogglue.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::xxl_job;

const std::string XxlJobLogglue::Cols::_id = "id";
const std::string XxlJobLogglue::Cols::_job_id = "job_id";
const std::string XxlJobLogglue::Cols::_glue_type = "glue_type";
const std::string XxlJobLogglue::Cols::_glue_source = "glue_source";
const std::string XxlJobLogglue::Cols::_glue_remark = "glue_remark";
const std::string XxlJobLogglue::Cols::_add_time = "add_time";
const std::string XxlJobLogglue::Cols::_update_time = "update_time";
const std::string XxlJobLogglue::primaryKeyName = "id";
const bool XxlJobLogglue::hasPrimaryKey = true;
const std::string XxlJobLogglue::tableName = "xxl_job_logglue";

const std::vector<typename XxlJobLogglue::MetaData> XxlJobLogglue::metaData_={
{"id","int32_t","int(11)",4,1,1,1},
{"job_id","int32_t","int(11)",4,0,0,1},
{"glue_type","std::string","varchar(50)",50,0,0,0},
{"glue_source","std::string","mediumtext",0,0,0,0},
{"glue_remark","std::string","varchar(128)",128,0,0,1},
{"add_time","::trantor::Date","datetime",0,0,0,0},
{"update_time","::trantor::Date","datetime",0,0,0,0}
};
const std::string &XxlJobLogglue::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
XxlJobLogglue::XxlJobLogglue(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["job_id"].isNull())
        {
            jobId_=std::make_shared<int32_t>(r["job_id"].as<int32_t>());
        }
        if(!r["glue_type"].isNull())
        {
            glueType_=std::make_shared<std::string>(r["glue_type"].as<std::string>());
        }
        if(!r["glue_source"].isNull())
        {
            glueSource_=std::make_shared<std::string>(r["glue_source"].as<std::string>());
        }
        if(!r["glue_remark"].isNull())
        {
            glueRemark_=std::make_shared<std::string>(r["glue_remark"].as<std::string>());
        }
        if(!r["add_time"].isNull())
        {
            auto timeStr = r["add_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                addTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["update_time"].isNull())
        {
            auto timeStr = r["update_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            jobId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            glueType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            glueSource_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            glueRemark_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                addTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

XxlJobLogglue::XxlJobLogglue(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            jobId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            glueType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            glueSource_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            glueRemark_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                addTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

XxlJobLogglue::XxlJobLogglue(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("job_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["job_id"].isNull())
        {
            jobId_=std::make_shared<int32_t>((int32_t)pJson["job_id"].asInt64());
        }
    }
    if(pJson.isMember("glue_type"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["glue_type"].isNull())
        {
            glueType_=std::make_shared<std::string>(pJson["glue_type"].asString());
        }
    }
    if(pJson.isMember("glue_source"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["glue_source"].isNull())
        {
            glueSource_=std::make_shared<std::string>(pJson["glue_source"].asString());
        }
    }
    if(pJson.isMember("glue_remark"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["glue_remark"].isNull())
        {
            glueRemark_=std::make_shared<std::string>(pJson["glue_remark"].asString());
        }
    }
    if(pJson.isMember("add_time"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["add_time"].isNull())
        {
            auto timeStr = pJson["add_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                addTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("update_time"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["update_time"].isNull())
        {
            auto timeStr = pJson["update_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void XxlJobLogglue::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            jobId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            glueType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            glueSource_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            glueRemark_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                addTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void XxlJobLogglue::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("job_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["job_id"].isNull())
        {
            jobId_=std::make_shared<int32_t>((int32_t)pJson["job_id"].asInt64());
        }
    }
    if(pJson.isMember("glue_type"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["glue_type"].isNull())
        {
            glueType_=std::make_shared<std::string>(pJson["glue_type"].asString());
        }
    }
    if(pJson.isMember("glue_source"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["glue_source"].isNull())
        {
            glueSource_=std::make_shared<std::string>(pJson["glue_source"].asString());
        }
    }
    if(pJson.isMember("glue_remark"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["glue_remark"].isNull())
        {
            glueRemark_=std::make_shared<std::string>(pJson["glue_remark"].asString());
        }
    }
    if(pJson.isMember("add_time"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["add_time"].isNull())
        {
            auto timeStr = pJson["add_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                addTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("update_time"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["update_time"].isNull())
        {
            auto timeStr = pJson["update_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &XxlJobLogglue::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &XxlJobLogglue::getId() const noexcept
{
    return id_;
}
void XxlJobLogglue::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename XxlJobLogglue::PrimaryKeyType & XxlJobLogglue::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &XxlJobLogglue::getValueOfJobId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(jobId_)
        return *jobId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &XxlJobLogglue::getJobId() const noexcept
{
    return jobId_;
}
void XxlJobLogglue::setJobId(const int32_t &pJobId) noexcept
{
    jobId_ = std::make_shared<int32_t>(pJobId);
    dirtyFlag_[1] = true;
}

const std::string &XxlJobLogglue::getValueOfGlueType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(glueType_)
        return *glueType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &XxlJobLogglue::getGlueType() const noexcept
{
    return glueType_;
}
void XxlJobLogglue::setGlueType(const std::string &pGlueType) noexcept
{
    glueType_ = std::make_shared<std::string>(pGlueType);
    dirtyFlag_[2] = true;
}
void XxlJobLogglue::setGlueType(std::string &&pGlueType) noexcept
{
    glueType_ = std::make_shared<std::string>(std::move(pGlueType));
    dirtyFlag_[2] = true;
}
void XxlJobLogglue::setGlueTypeToNull() noexcept
{
    glueType_.reset();
    dirtyFlag_[2] = true;
}

const std::string &XxlJobLogglue::getValueOfGlueSource() const noexcept
{
    static const std::string defaultValue = std::string();
    if(glueSource_)
        return *glueSource_;
    return defaultValue;
}
const std::shared_ptr<std::string> &XxlJobLogglue::getGlueSource() const noexcept
{
    return glueSource_;
}
void XxlJobLogglue::setGlueSource(const std::string &pGlueSource) noexcept
{
    glueSource_ = std::make_shared<std::string>(pGlueSource);
    dirtyFlag_[3] = true;
}
void XxlJobLogglue::setGlueSource(std::string &&pGlueSource) noexcept
{
    glueSource_ = std::make_shared<std::string>(std::move(pGlueSource));
    dirtyFlag_[3] = true;
}
void XxlJobLogglue::setGlueSourceToNull() noexcept
{
    glueSource_.reset();
    dirtyFlag_[3] = true;
}

const std::string &XxlJobLogglue::getValueOfGlueRemark() const noexcept
{
    static const std::string defaultValue = std::string();
    if(glueRemark_)
        return *glueRemark_;
    return defaultValue;
}
const std::shared_ptr<std::string> &XxlJobLogglue::getGlueRemark() const noexcept
{
    return glueRemark_;
}
void XxlJobLogglue::setGlueRemark(const std::string &pGlueRemark) noexcept
{
    glueRemark_ = std::make_shared<std::string>(pGlueRemark);
    dirtyFlag_[4] = true;
}
void XxlJobLogglue::setGlueRemark(std::string &&pGlueRemark) noexcept
{
    glueRemark_ = std::make_shared<std::string>(std::move(pGlueRemark));
    dirtyFlag_[4] = true;
}

const ::trantor::Date &XxlJobLogglue::getValueOfAddTime() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(addTime_)
        return *addTime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &XxlJobLogglue::getAddTime() const noexcept
{
    return addTime_;
}
void XxlJobLogglue::setAddTime(const ::trantor::Date &pAddTime) noexcept
{
    addTime_ = std::make_shared<::trantor::Date>(pAddTime);
    dirtyFlag_[5] = true;
}
void XxlJobLogglue::setAddTimeToNull() noexcept
{
    addTime_.reset();
    dirtyFlag_[5] = true;
}

const ::trantor::Date &XxlJobLogglue::getValueOfUpdateTime() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updateTime_)
        return *updateTime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &XxlJobLogglue::getUpdateTime() const noexcept
{
    return updateTime_;
}
void XxlJobLogglue::setUpdateTime(const ::trantor::Date &pUpdateTime) noexcept
{
    updateTime_ = std::make_shared<::trantor::Date>(pUpdateTime);
    dirtyFlag_[6] = true;
}
void XxlJobLogglue::setUpdateTimeToNull() noexcept
{
    updateTime_.reset();
    dirtyFlag_[6] = true;
}

void XxlJobLogglue::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &XxlJobLogglue::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "job_id",
        "glue_type",
        "glue_source",
        "glue_remark",
        "add_time",
        "update_time"
    };
    return inCols;
}

void XxlJobLogglue::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getJobId())
        {
            binder << getValueOfJobId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getGlueType())
        {
            binder << getValueOfGlueType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getGlueSource())
        {
            binder << getValueOfGlueSource();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getGlueRemark())
        {
            binder << getValueOfGlueRemark();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAddTime())
        {
            binder << getValueOfAddTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getUpdateTime())
        {
            binder << getValueOfUpdateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> XxlJobLogglue::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void XxlJobLogglue::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getJobId())
        {
            binder << getValueOfJobId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getGlueType())
        {
            binder << getValueOfGlueType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getGlueSource())
        {
            binder << getValueOfGlueSource();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getGlueRemark())
        {
            binder << getValueOfGlueRemark();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAddTime())
        {
            binder << getValueOfAddTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getUpdateTime())
        {
            binder << getValueOfUpdateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value XxlJobLogglue::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getJobId())
    {
        ret["job_id"]=getValueOfJobId();
    }
    else
    {
        ret["job_id"]=Json::Value();
    }
    if(getGlueType())
    {
        ret["glue_type"]=getValueOfGlueType();
    }
    else
    {
        ret["glue_type"]=Json::Value();
    }
    if(getGlueSource())
    {
        ret["glue_source"]=getValueOfGlueSource();
    }
    else
    {
        ret["glue_source"]=Json::Value();
    }
    if(getGlueRemark())
    {
        ret["glue_remark"]=getValueOfGlueRemark();
    }
    else
    {
        ret["glue_remark"]=Json::Value();
    }
    if(getAddTime())
    {
        ret["add_time"]=getAddTime()->toDbStringLocal();
    }
    else
    {
        ret["add_time"]=Json::Value();
    }
    if(getUpdateTime())
    {
        ret["update_time"]=getUpdateTime()->toDbStringLocal();
    }
    else
    {
        ret["update_time"]=Json::Value();
    }
    return ret;
}

Json::Value XxlJobLogglue::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getJobId())
            {
                ret[pMasqueradingVector[1]]=getValueOfJobId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getGlueType())
            {
                ret[pMasqueradingVector[2]]=getValueOfGlueType();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getGlueSource())
            {
                ret[pMasqueradingVector[3]]=getValueOfGlueSource();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getGlueRemark())
            {
                ret[pMasqueradingVector[4]]=getValueOfGlueRemark();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getAddTime())
            {
                ret[pMasqueradingVector[5]]=getAddTime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getUpdateTime())
            {
                ret[pMasqueradingVector[6]]=getUpdateTime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getJobId())
    {
        ret["job_id"]=getValueOfJobId();
    }
    else
    {
        ret["job_id"]=Json::Value();
    }
    if(getGlueType())
    {
        ret["glue_type"]=getValueOfGlueType();
    }
    else
    {
        ret["glue_type"]=Json::Value();
    }
    if(getGlueSource())
    {
        ret["glue_source"]=getValueOfGlueSource();
    }
    else
    {
        ret["glue_source"]=Json::Value();
    }
    if(getGlueRemark())
    {
        ret["glue_remark"]=getValueOfGlueRemark();
    }
    else
    {
        ret["glue_remark"]=Json::Value();
    }
    if(getAddTime())
    {
        ret["add_time"]=getAddTime()->toDbStringLocal();
    }
    else
    {
        ret["add_time"]=Json::Value();
    }
    if(getUpdateTime())
    {
        ret["update_time"]=getUpdateTime()->toDbStringLocal();
    }
    else
    {
        ret["update_time"]=Json::Value();
    }
    return ret;
}

bool XxlJobLogglue::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("job_id"))
    {
        if(!validJsonOfField(1, "job_id", pJson["job_id"], err, true))
            return false;
    }
    else
    {
        err="The job_id column cannot be null";
        return false;
    }
    if(pJson.isMember("glue_type"))
    {
        if(!validJsonOfField(2, "glue_type", pJson["glue_type"], err, true))
            return false;
    }
    if(pJson.isMember("glue_source"))
    {
        if(!validJsonOfField(3, "glue_source", pJson["glue_source"], err, true))
            return false;
    }
    if(pJson.isMember("glue_remark"))
    {
        if(!validJsonOfField(4, "glue_remark", pJson["glue_remark"], err, true))
            return false;
    }
    else
    {
        err="The glue_remark column cannot be null";
        return false;
    }
    if(pJson.isMember("add_time"))
    {
        if(!validJsonOfField(5, "add_time", pJson["add_time"], err, true))
            return false;
    }
    if(pJson.isMember("update_time"))
    {
        if(!validJsonOfField(6, "update_time", pJson["update_time"], err, true))
            return false;
    }
    return true;
}
bool XxlJobLogglue::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool XxlJobLogglue::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("job_id"))
    {
        if(!validJsonOfField(1, "job_id", pJson["job_id"], err, false))
            return false;
    }
    if(pJson.isMember("glue_type"))
    {
        if(!validJsonOfField(2, "glue_type", pJson["glue_type"], err, false))
            return false;
    }
    if(pJson.isMember("glue_source"))
    {
        if(!validJsonOfField(3, "glue_source", pJson["glue_source"], err, false))
            return false;
    }
    if(pJson.isMember("glue_remark"))
    {
        if(!validJsonOfField(4, "glue_remark", pJson["glue_remark"], err, false))
            return false;
    }
    if(pJson.isMember("add_time"))
    {
        if(!validJsonOfField(5, "add_time", pJson["add_time"], err, false))
            return false;
    }
    if(pJson.isMember("update_time"))
    {
        if(!validJsonOfField(6, "update_time", pJson["update_time"], err, false))
            return false;
    }
    return true;
}
bool XxlJobLogglue::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool XxlJobLogglue::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
