/**
 *
 *  XxlJobLogglue.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace xxl_job
{

class XxlJobLogglue
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _job_id;
        static const std::string _glue_type;
        static const std::string _glue_source;
        static const std::string _glue_remark;
        static const std::string _add_time;
        static const std::string _update_time;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit XxlJobLogglue(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit XxlJobLogglue(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    XxlJobLogglue(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    XxlJobLogglue() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column job_id  */
    ///Get the value of the column job_id, returns the default value if the column is null
    const int32_t &getValueOfJobId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getJobId() const noexcept;
    ///Set the value of the column job_id
    void setJobId(const int32_t &pJobId) noexcept;

    /**  For column glue_type  */
    ///Get the value of the column glue_type, returns the default value if the column is null
    const std::string &getValueOfGlueType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getGlueType() const noexcept;
    ///Set the value of the column glue_type
    void setGlueType(const std::string &pGlueType) noexcept;
    void setGlueType(std::string &&pGlueType) noexcept;
    void setGlueTypeToNull() noexcept;

    /**  For column glue_source  */
    ///Get the value of the column glue_source, returns the default value if the column is null
    const std::string &getValueOfGlueSource() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getGlueSource() const noexcept;
    ///Set the value of the column glue_source
    void setGlueSource(const std::string &pGlueSource) noexcept;
    void setGlueSource(std::string &&pGlueSource) noexcept;
    void setGlueSourceToNull() noexcept;

    /**  For column glue_remark  */
    ///Get the value of the column glue_remark, returns the default value if the column is null
    const std::string &getValueOfGlueRemark() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getGlueRemark() const noexcept;
    ///Set the value of the column glue_remark
    void setGlueRemark(const std::string &pGlueRemark) noexcept;
    void setGlueRemark(std::string &&pGlueRemark) noexcept;

    /**  For column add_time  */
    ///Get the value of the column add_time, returns the default value if the column is null
    const ::trantor::Date &getValueOfAddTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getAddTime() const noexcept;
    ///Set the value of the column add_time
    void setAddTime(const ::trantor::Date &pAddTime) noexcept;
    void setAddTimeToNull() noexcept;

    /**  For column update_time  */
    ///Get the value of the column update_time, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdateTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdateTime() const noexcept;
    ///Set the value of the column update_time
    void setUpdateTime(const ::trantor::Date &pUpdateTime) noexcept;
    void setUpdateTimeToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 7;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<XxlJobLogglue>;
    friend drogon::orm::BaseBuilder<XxlJobLogglue, true, true>;
    friend drogon::orm::BaseBuilder<XxlJobLogglue, true, false>;
    friend drogon::orm::BaseBuilder<XxlJobLogglue, false, true>;
    friend drogon::orm::BaseBuilder<XxlJobLogglue, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<XxlJobLogglue>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<int32_t> jobId_;
    std::shared_ptr<std::string> glueType_;
    std::shared_ptr<std::string> glueSource_;
    std::shared_ptr<std::string> glueRemark_;
    std::shared_ptr<::trantor::Date> addTime_;
    std::shared_ptr<::trantor::Date> updateTime_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[7]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "job_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "glue_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "glue_source,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "glue_remark,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "add_time,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "update_time,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace xxl_job
} // namespace drogon_model
